const pdfData = [
    { nombre: "2D_AOI_Algorithm_BestPractise_cookbook_Rev1.pdf", descripcion: "Guia rapida para depuración", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "3D AOI - Unpopulated Area Inspection.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "3D AOI Algorithm Best Practice Cookbook.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "3D Electrical Drawing Rev 05_Aug 2017.PDF", descripcion: "	", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "camera and lighting calibration.pdf", descripcion: "Calibracion de camaras y luces", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "G2s EE Drawing.pdf", descripcion: "Diagrama Electrico", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "JetPower 2.0.0.23 MainGUI Training Material.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "PC Recommendation for AOI _ AXI Software_rev7.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "Unpopulated Area Inspection.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "V510 How To Clean Your Lens_Rev1.pdf", descripcion: "Como limpiar el lente de la camara", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "V510 Standard SMEMA Proposal.pdf", descripcion: "	", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "ViTrox V510 3D AOI Site Preparation Manual RevA.pdf", descripcion: "Consideraciones para el sitio de instalación de la v510", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "ViTrox V510i Optimus 3D Brochure.pdf", descripcion: "Especificaciones rapidas v510", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "ViTrox V510_EED.pdf", descripcion: "Diagrama electrico v510", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "ViTrox V510_HM.pdf", descripcion: "Manual de Hadware v510", category: "AOI-Vitrox-Proveedor-Hadware" },
    { nombre: "VVTS 3.01.12 User Guide.pdf", descripcion: "Manual de la VVTS", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "VVTS Advanced Setup 3.00.01 Application Note.pdf", descripcion: "Configuraciones avanzadas VVTS", category: "AOI-Vitrox-Proveedor-Software" },
    { nombre: "1. VAYO.pdf", descripcion: "	Curso básico para la generación  de programas en AOI VITROX	", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "1.1. PLX- Long Board.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX	", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "2. Fiduciales.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "3. Merge Database.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofwar	" },
    { nombre: "3.1 Good Image_save tiles.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "4. Resistencias & Capacitores.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "5. B-Type.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "6. S-Type.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "7.2 Polarity_ Height(Alturas).pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "7.3 OCV & OCR.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "9. Panelizado manual.pdf", descripcion: "Curso básico para la generación  de programas en AOI VITROX", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "Mantenimiento  AXI", descripcion: "Mantenimiento preventivo AXI", category: "AXI-Sanmina-Hadware" },
    { nombre: "Mapeo AOI.pdf", descripcion: "Mapeo AOI Saki", category: "AOI-Saki-Sanmina-Sofware" },
    { nombre: "Parte 1. ePM.pdf", descripcion: "Creación de programa Saki mediante ePM", category: "AOI-Saki-Sanmina-Sofware" },
    { nombre: "Reportes Semanales Saki.pdf", descripcion: "Como generar reportes semanales en Saki", category: "AOI-Saki-Sanmina-Sofware" },
    { nombre: "Tiles.pdf", descripcion: "Como generar Tiles", category: "AOI-Vitrox-Sanmina-Sofware" },
    { nombre: "XY Failure AOI 599B.pdf", descripcion: "Falla de XY en AOI", category: "AOI-Saki-Sanmina-Hadware" },
    { nombre: "02 3D Training HW Print.pdf", descripcion: "Mantenimientos para el Hadware", category: "AOI-Saki-Proveedor-Hadware" },
	{ nombre: "3D AOI Programming Manual.pdf", descripcion: "Manual de programación 3D", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "BF-3Di-L1_Z1_Replacement of the Conveyor Belt and pulleys.pdf", descripcion: "Reemplazo de conveyor", category: "AOI-Saki-Proveedor-Hadware" },
	{ nombre: "BF1.pdf", descripcion: "Instalación de BF1", category: "AOI-Saki-Sanmina-Sofware" },
	{ nombre: "CALIBRACION AOI LS.pdf", descripcion: "Manual de calibración Modelos: 3Di-xx2, 3Si-xx2", category: "AOI-Saki-Proveedor-Hadware" },
	{ nombre: "Calibrate BF-3Di-L1_D1_Z1_x1a.pdf", descripcion: "Manual de calibración Modelos: BF-3Di-L1, BF-3Di-D1, BF-3Di-Z1", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "Programming Manual.pdf", descripcion: "Manual de programacion Saki", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "SAKI 3Di Programming-HW Level 2 training.pdf", descripcion: "Guia rapida de Saki", category: "AOI-Saki-Proveedor-Hadware" },
	{ nombre: "TSM16002-02EA_1.0_Calibrate BF-3Di-L1_D1_Z1_x1a.pdf", descripcion: "", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM15020-01EA]RMS_Remote_Management_System 3D.pdf", descripcion: "Sistema de control multiple remoto", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM15024-02EA]Board_surface_height_compensation_DOP_Compensation.pdf", descripcion: "Explicación del DOP", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM15028-04EA]LargeSizePcbPrograming.pdf", descripcion: "Explicación de tarjetas grandes", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM18038-05EA]Self_Tuning.pdf", descripcion: "", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM20003-03EN]SideCamera_(BF2-ver3.4).pdf", descripcion: "Camaras angulares", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM20029-03EA]Offline Debug Improvement.pdf", descripcion: "", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM20052-01EA]Saki Self Programming for v3.5.pdf", descripcion: "Creación de programa", category: "AOI-Saki-Proveedor-Sofware" },
	{ nombre: "[SFM20103-03EA]SolderingCondition_0.0.0.3.pdf", descripcion: "Explicación de soldabilidad", category: "AOI-Saki-Proveedor-Sofware" },
];